//
//  MLoginResult
//  M1Core
//
//  Created by Generated by Java on 2014-06-26 13:54.
//  Copyright (c) 2012年 北京致远协创软件有限公司. All rights reserved.
//

@class MOrgMember;
#import "SKBaseObject.h"


@interface SKLoginResult : SKBaseObject
{
    NSString        *token;
    NSArray        *resourceList;
//    MOrgMember        *currentUser;
    NSInteger        loginResult;
    NSInteger        loginDesc;
    BOOL        groupVer;
    BOOL        hasSignetures;
    BOOL        hasOfficePlugin;
    NSString        *mapProvider;
    BOOL        govVer;
    NSDictionary        *extAttrs;

}
@property(nonatomic, copy)NSString        *token;
@property(nonatomic, retain)NSArray        *resourceList;
//@property(nonatomic, retain)MOrgMember        *currentUser;
@property(nonatomic, assign)NSInteger        loginResult;
@property(nonatomic, assign)NSInteger        loginDesc;
@property(nonatomic, assign)BOOL        groupVer;
@property(nonatomic, assign)BOOL        hasSignetures;
@property(nonatomic, assign)BOOL        hasOfficePlugin;
@property(nonatomic, copy)NSString        *mapProvider;
@property(nonatomic, assign)BOOL        govVer;
@property(nonatomic, retain)NSDictionary        *extAttrs;

@end
