//
//  MLoginResult
//  M1Core
//
//  Created by Generated by Java on 2014-06-26 13:54.
//  Copyright (c) 2012年 北京致远协创软件有限公司. All rights reserved.
//

//#import "MOrgMember.h"
#import "SKLoginResult.h"

@implementation SKLoginResult
@synthesize  token;
@synthesize  resourceList;
//@synthesize  currentUser;
@synthesize  loginResult;
@synthesize  loginDesc;
@synthesize  groupVer;
@synthesize  hasSignetures;
@synthesize  hasOfficePlugin;
@synthesize  mapProvider;
@synthesize  govVer;
@synthesize  extAttrs;


- (void)dealloc
{
    [token release];
    [resourceList release];
//    [currentUser release];
    [mapProvider release];
    [extAttrs release];

    [super dealloc];
}
@end
