//
//  MCollaborationListItem
//  M1Core
//
//  Created by Generated by Java on 2015-01-12 17:32.
//  Copyright (c) 2012年 北京致远协创软件有限公司. All rights reserved.
//

#import "MMemberIcon.h"
#import "MCollaborationListItem.h"

@implementation MCollaborationListItem
@synthesize  summaryID;
@synthesize  affairID;
@synthesize  affairState;
@synthesize  affairSubState;
@synthesize  flowState;
@synthesize  track;
@synthesize  proxy;
@synthesize  proxyName;
@synthesize  overdue;
@synthesize  icon;
@synthesize  formFlow;
@synthesize  rightID;
@synthesize  beBack;
@synthesize  originalForm;
@synthesize  receiveDate;
@synthesize  dealDate;


- (void)dealloc
{
    [proxyName release];
    [overdue release];
    [icon release];
    [rightID release];
    [receiveDate release];
    [dealDate release];

    [super dealloc];
}
@end
