//
//  MListItem
//  M1Core
//
//  Created by Generated by Java on 2014-08-15 10:41.
//  Copyright (c) 2012年 北京致远协创软件有限公司. All rights reserved.
//

@class MMemberIcon;
#import "SKBaseObject.h"




@interface MListItem : SKBaseObject
{
    NSString        *title;
    NSInteger        importLevel;
    long long        startMemberID;
    NSString        *startMemberName;
    BOOL        hasAttsFlag;
    NSString        *createDate;
    NSInteger        moduleType;
    BOOL        readFlag;
    NSString        *contextJson;
    long long        belongUserID;
    NSString        *belongUserName;
    MMemberIcon        *belongUserIcon;
    NSInteger        handSelectOptionsNumber;
    BOOL        locked;
    NSString        *lockedMessage;

}
@property(nonatomic, copy)NSString        *title;
@property(nonatomic, assign)NSInteger        importLevel;
@property(nonatomic, assign)long long        startMemberID;
@property(nonatomic, copy)NSString        *startMemberName;
@property(nonatomic, assign)BOOL        hasAttsFlag;
@property(nonatomic, copy)NSString        *createDate;
@property(nonatomic, assign)NSInteger        moduleType;
@property(nonatomic, assign)BOOL        readFlag;
@property(nonatomic, copy)NSString        *contextJson;
@property(nonatomic, assign)long long        belongUserID;
@property(nonatomic, copy)NSString        *belongUserName;
@property(nonatomic, retain)MMemberIcon        *belongUserIcon;
@property(nonatomic, assign)NSInteger        handSelectOptionsNumber;
@property(nonatomic, assign)BOOL        locked;
@property(nonatomic, copy)NSString        *lockedMessage;

@end
