//
//  MListItem
//  M1Core
//
//  Created by Generated by Java on 2014-08-15 10:41.
//  Copyright (c) 2012年 北京致远协创软件有限公司. All rights reserved.
//

#import "MMemberIcon.h"
#import "MListItem.h"

@implementation MListItem
@synthesize  title;
@synthesize  importLevel;
@synthesize  startMemberID;
@synthesize  startMemberName;
@synthesize  hasAttsFlag;
@synthesize  createDate;
@synthesize  moduleType;
@synthesize  readFlag;
@synthesize  contextJson;
@synthesize  belongUserID;
@synthesize  belongUserName;
@synthesize  belongUserIcon;
@synthesize  handSelectOptionsNumber;
@synthesize  locked;
@synthesize  lockedMessage;


- (void)dealloc
{
    [title release];
    [startMemberName release];
    [createDate release];
    [contextJson release];
    [belongUserName release];
    [belongUserIcon release];
    [lockedMessage release];

    [super dealloc];
}
@end
