//
//  MCollaborationListItem
//  M1Core
//
//  Created by Generated by Java on 2015-01-12 17:32.
//  Copyright (c) 2012年 北京致远协创软件有限公司. All rights reserved.
//

@class MMemberIcon;
#import "MListItem.h"




@interface MCollaborationListItem : MListItem
{
    long long        summaryID;
    long long        affairID;
    NSInteger        affairState;
    NSInteger        affairSubState;
    NSInteger        flowState;
    BOOL        track;
    BOOL        proxy;
    NSString        *proxyName;
    NSString        *overdue;
    MMemberIcon        *icon;
    BOOL        formFlow;
    NSString        *rightID;
    BOOL        beBack;
    BOOL        originalForm;
    NSString        *receiveDate;
    NSString        *dealDate;

}
@property(nonatomic, assign)long long        summaryID;
@property(nonatomic, assign)long long        affairID;
@property(nonatomic, assign)NSInteger        affairState;
@property(nonatomic, assign)NSInteger        affairSubState;
@property(nonatomic, assign)NSInteger        flowState;
@property(nonatomic, assign)BOOL        track;
@property(nonatomic, assign)BOOL        proxy;
@property(nonatomic, copy)NSString        *proxyName;
@property(nonatomic, copy)NSString        *overdue;
@property(nonatomic, retain)MMemberIcon        *icon;
@property(nonatomic, assign)BOOL        formFlow;
@property(nonatomic, copy)NSString        *rightID;
@property(nonatomic, assign)BOOL        beBack;
@property(nonatomic, assign)BOOL        originalForm;
@property(nonatomic, copy)NSString        *receiveDate;
@property(nonatomic, copy)NSString        *dealDate;

@end
