//
//  MMemberIcon
//  M1Core
//
//  Created by Generated by Java on 2014-04-16 15:28.
//  Copyright (c) 2012年 北京致远协创软件有限公司. All rights reserved.
//

#import "SKBaseObject.h"




@interface MMemberIcon : SKBaseObject<NSCoding>
{
    NSString        *iconPath;
    long long        size;
    NSString        *lastModifyDate;
    NSInteger        iconType;

}
@property(nonatomic, copy)NSString        *iconPath;
@property(nonatomic, assign)long long        size;
@property(nonatomic, copy)NSString        *lastModifyDate;
@property(nonatomic, assign)NSInteger        iconType;

@end
